{ mkBunDerivation, ... }:

# React Storybook static site built via bun2nix for kennel deployment.
# Requires bun.nix at the repo root (regenerated by the root package.json
# postinstall script every time `bun install` runs).
mkBunDerivation {
  pname = "storybook-react";
  version = "0.0.0";

  src = ../.;
  bunNix = ../bun.nix;
  packageJson = ../package.json;

  buildPhase = ''
    runHook preBuild
    bun run --filter '@scottylabs/storybook-react' build
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p $out
    cp -r apps/storybook-react/storybook-static/. $out/
    runHook postInstall
  '';
}
